//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace EWFM.AwacsMes.phcab01vww01 {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="Ad_HocTxnSoap", Namespace="http://tempuri.org/")]
    public partial class Ad_HocTxn : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetVersionOperationCompleted;
        
        private System.Threading.SendOrPostCallback LotHoldOperationCompleted;
        
        private System.Threading.SendOrPostCallback LotReleaseOperationCompleted;
        
        private System.Threading.SendOrPostCallback ModifyLotHoldcodeOperationCompleted;
        
        private System.Threading.SendOrPostCallback LotFutureHoldSetupOperationCompleted;
        
        private System.Threading.SendOrPostCallback ModifyLotAttributeOperationCompleted;
        
        private System.Threading.SendOrPostCallback FutureHoldSetupByDiffusionBatchOperationCompleted;
        
        private System.Threading.SendOrPostCallback RemoveFutureHoldSetupOperationCompleted;
        
        private System.Threading.SendOrPostCallback ModifyLotItemsOperationCompleted;
        
        private System.Threading.SendOrPostCallback LotHoldDisposeOperationCompleted;
        
        private System.Threading.SendOrPostCallback LotHoldTransactionOperationCompleted;
        
        private System.Threading.SendOrPostCallback RemoveLotFutureHoldOperationCompleted;
        
        private System.Threading.SendOrPostCallback LotModifyMarkingContentOperationCompleted;
        
        private System.Threading.SendOrPostCallback AddVendorNameOperationCompleted;
        
        private System.Threading.SendOrPostCallback PrintingOperationCompleted;
        
        private System.Threading.SendOrPostCallback LotAddSIOperationCompleted;
        
        private System.Threading.SendOrPostCallback LotReleaseSIOperationCompleted;
        
        private System.Threading.SendOrPostCallback LotReleaseSIWithNcrbNumberOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetQueryResultOperationCompleted;
        
        private System.Threading.SendOrPostCallback ModifyLotReelsOperationCompleted;
        
        private System.Threading.SendOrPostCallback LotAddSiWithNCRBOperationCompleted;
        
        private System.Threading.SendOrPostCallback LotReleaseSiWithNCRBOperationCompleted;
        
        private System.Threading.SendOrPostCallback LotEquipmentReservationOperationCompleted;
        
        private System.Threading.SendOrPostCallback LotCombineOperationCompleted;
        
        private System.Threading.SendOrPostCallback AddEquipmentBlockStatusOperationCompleted;
        
        private System.Threading.SendOrPostCallback RealeaseEquipmentBlockStatusOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Ad_HocTxn() {
            this.Url = global::EWFM.AwacsMes.Properties.Settings.Default.AwacsMesService_phcab01vww01_Ad_HocTxn;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetVersionCompletedEventHandler GetVersionCompleted;
        
        /// <remarks/>
        public event LotHoldCompletedEventHandler LotHoldCompleted;
        
        /// <remarks/>
        public event LotReleaseCompletedEventHandler LotReleaseCompleted;
        
        /// <remarks/>
        public event ModifyLotHoldcodeCompletedEventHandler ModifyLotHoldcodeCompleted;
        
        /// <remarks/>
        public event LotFutureHoldSetupCompletedEventHandler LotFutureHoldSetupCompleted;
        
        /// <remarks/>
        public event ModifyLotAttributeCompletedEventHandler ModifyLotAttributeCompleted;
        
        /// <remarks/>
        public event FutureHoldSetupByDiffusionBatchCompletedEventHandler FutureHoldSetupByDiffusionBatchCompleted;
        
        /// <remarks/>
        public event RemoveFutureHoldSetupCompletedEventHandler RemoveFutureHoldSetupCompleted;
        
        /// <remarks/>
        public event ModifyLotItemsCompletedEventHandler ModifyLotItemsCompleted;
        
        /// <remarks/>
        public event LotHoldDisposeCompletedEventHandler LotHoldDisposeCompleted;
        
        /// <remarks/>
        public event LotHoldTransactionCompletedEventHandler LotHoldTransactionCompleted;
        
        /// <remarks/>
        public event RemoveLotFutureHoldCompletedEventHandler RemoveLotFutureHoldCompleted;
        
        /// <remarks/>
        public event LotModifyMarkingContentCompletedEventHandler LotModifyMarkingContentCompleted;
        
        /// <remarks/>
        public event AddVendorNameCompletedEventHandler AddVendorNameCompleted;
        
        /// <remarks/>
        public event PrintingCompletedEventHandler PrintingCompleted;
        
        /// <remarks/>
        public event LotAddSICompletedEventHandler LotAddSICompleted;
        
        /// <remarks/>
        public event LotReleaseSICompletedEventHandler LotReleaseSICompleted;
        
        /// <remarks/>
        public event LotReleaseSIWithNcrbNumberCompletedEventHandler LotReleaseSIWithNcrbNumberCompleted;
        
        /// <remarks/>
        public event GetQueryResultCompletedEventHandler GetQueryResultCompleted;
        
        /// <remarks/>
        public event ModifyLotReelsCompletedEventHandler ModifyLotReelsCompleted;
        
        /// <remarks/>
        public event LotAddSiWithNCRBCompletedEventHandler LotAddSiWithNCRBCompleted;
        
        /// <remarks/>
        public event LotReleaseSiWithNCRBCompletedEventHandler LotReleaseSiWithNCRBCompleted;
        
        /// <remarks/>
        public event LotEquipmentReservationCompletedEventHandler LotEquipmentReservationCompleted;
        
        /// <remarks/>
        public event LotCombineCompletedEventHandler LotCombineCompleted;
        
        /// <remarks/>
        public event AddEquipmentBlockStatusCompletedEventHandler AddEquipmentBlockStatusCompleted;
        
        /// <remarks/>
        public event RealeaseEquipmentBlockStatusCompletedEventHandler RealeaseEquipmentBlockStatusCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetVersion", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Xml.XmlNode GetVersion() {
            object[] results = this.Invoke("GetVersion", new object[0]);
            return ((System.Xml.XmlNode)(results[0]));
        }
        
        /// <remarks/>
        public void GetVersionAsync() {
            this.GetVersionAsync(null);
        }
        
        /// <remarks/>
        public void GetVersionAsync(object userState) {
            if ((this.GetVersionOperationCompleted == null)) {
                this.GetVersionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetVersionOperationCompleted);
            }
            this.InvokeAsync("GetVersion", new object[0], this.GetVersionOperationCompleted, userState);
        }
        
        private void OnGetVersionOperationCompleted(object arg) {
            if ((this.GetVersionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetVersionCompleted(this, new GetVersionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/LotHold", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Xml.XmlNode LotHold(string container, string holdLocation, string holdReason, string comment, string employee) {
            object[] results = this.Invoke("LotHold", new object[] {
                        container,
                        holdLocation,
                        holdReason,
                        comment,
                        employee});
            return ((System.Xml.XmlNode)(results[0]));
        }
        
        /// <remarks/>
        public void LotHoldAsync(string container, string holdLocation, string holdReason, string comment, string employee) {
            this.LotHoldAsync(container, holdLocation, holdReason, comment, employee, null);
        }
        
        /// <remarks/>
        public void LotHoldAsync(string container, string holdLocation, string holdReason, string comment, string employee, object userState) {
            if ((this.LotHoldOperationCompleted == null)) {
                this.LotHoldOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLotHoldOperationCompleted);
            }
            this.InvokeAsync("LotHold", new object[] {
                        container,
                        holdLocation,
                        holdReason,
                        comment,
                        employee}, this.LotHoldOperationCompleted, userState);
        }
        
        private void OnLotHoldOperationCompleted(object arg) {
            if ((this.LotHoldCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.LotHoldCompleted(this, new LotHoldCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/LotRelease", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Xml.XmlNode LotRelease(string container, string ReleaseAllHoldLocations, string ReleaseHoldLocationsOnly, string ReleaseReason, string holdcode, string ApplyToChildLots, string comment) {
            object[] results = this.Invoke("LotRelease", new object[] {
                        container,
                        ReleaseAllHoldLocations,
                        ReleaseHoldLocationsOnly,
                        ReleaseReason,
                        holdcode,
                        ApplyToChildLots,
                        comment});
            return ((System.Xml.XmlNode)(results[0]));
        }
        
        /// <remarks/>
        public void LotReleaseAsync(string container, string ReleaseAllHoldLocations, string ReleaseHoldLocationsOnly, string ReleaseReason, string holdcode, string ApplyToChildLots, string comment) {
            this.LotReleaseAsync(container, ReleaseAllHoldLocations, ReleaseHoldLocationsOnly, ReleaseReason, holdcode, ApplyToChildLots, comment, null);
        }
        
        /// <remarks/>
        public void LotReleaseAsync(string container, string ReleaseAllHoldLocations, string ReleaseHoldLocationsOnly, string ReleaseReason, string holdcode, string ApplyToChildLots, string comment, object userState) {
            if ((this.LotReleaseOperationCompleted == null)) {
                this.LotReleaseOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLotReleaseOperationCompleted);
            }
            this.InvokeAsync("LotRelease", new object[] {
                        container,
                        ReleaseAllHoldLocations,
                        ReleaseHoldLocationsOnly,
                        ReleaseReason,
                        holdcode,
                        ApplyToChildLots,
                        comment}, this.LotReleaseOperationCompleted, userState);
        }
        
        private void OnLotReleaseOperationCompleted(object arg) {
            if ((this.LotReleaseCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.LotReleaseCompleted(this, new LotReleaseCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ModifyLotHoldcode", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Xml.XmlNode ModifyLotHoldcode(string lot, string old_holdcode, string new_holdcode, string holdlocation, string comment, string employee) {
            object[] results = this.Invoke("ModifyLotHoldcode", new object[] {
                        lot,
                        old_holdcode,
                        new_holdcode,
                        holdlocation,
                        comment,
                        employee});
            return ((System.Xml.XmlNode)(results[0]));
        }
        
        /// <remarks/>
        public void ModifyLotHoldcodeAsync(string lot, string old_holdcode, string new_holdcode, string holdlocation, string comment, string employee) {
            this.ModifyLotHoldcodeAsync(lot, old_holdcode, new_holdcode, holdlocation, comment, employee, null);
        }
        
        /// <remarks/>
        public void ModifyLotHoldcodeAsync(string lot, string old_holdcode, string new_holdcode, string holdlocation, string comment, string employee, object userState) {
            if ((this.ModifyLotHoldcodeOperationCompleted == null)) {
                this.ModifyLotHoldcodeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnModifyLotHoldcodeOperationCompleted);
            }
            this.InvokeAsync("ModifyLotHoldcode", new object[] {
                        lot,
                        old_holdcode,
                        new_holdcode,
                        holdlocation,
                        comment,
                        employee}, this.ModifyLotHoldcodeOperationCompleted, userState);
        }
        
        private void OnModifyLotHoldcodeOperationCompleted(object arg) {
            if ((this.ModifyLotHoldcodeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ModifyLotHoldcodeCompleted(this, new ModifyLotHoldcodeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/LotFutureHoldSetup", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Xml.XmlNode LotFutureHoldSetup(string container, string spec, string specRev, string holdLocation, string holdReason, string expectedHoldDays, string comment) {
            object[] results = this.Invoke("LotFutureHoldSetup", new object[] {
                        container,
                        spec,
                        specRev,
                        holdLocation,
                        holdReason,
                        expectedHoldDays,
                        comment});
            return ((System.Xml.XmlNode)(results[0]));
        }
        
        /// <remarks/>
        public void LotFutureHoldSetupAsync(string container, string spec, string specRev, string holdLocation, string holdReason, string expectedHoldDays, string comment) {
            this.LotFutureHoldSetupAsync(container, spec, specRev, holdLocation, holdReason, expectedHoldDays, comment, null);
        }
        
        /// <remarks/>
        public void LotFutureHoldSetupAsync(string container, string spec, string specRev, string holdLocation, string holdReason, string expectedHoldDays, string comment, object userState) {
            if ((this.LotFutureHoldSetupOperationCompleted == null)) {
                this.LotFutureHoldSetupOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLotFutureHoldSetupOperationCompleted);
            }
            this.InvokeAsync("LotFutureHoldSetup", new object[] {
                        container,
                        spec,
                        specRev,
                        holdLocation,
                        holdReason,
                        expectedHoldDays,
                        comment}, this.LotFutureHoldSetupOperationCompleted, userState);
        }
        
        private void OnLotFutureHoldSetupOperationCompleted(object arg) {
            if ((this.LotFutureHoldSetupCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.LotFutureHoldSetupCompleted(this, new LotFutureHoldSetupCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ModifyLotAttribute", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Xml.XmlNode ModifyLotAttribute(string lot, string name, string value) {
            object[] results = this.Invoke("ModifyLotAttribute", new object[] {
                        lot,
                        name,
                        value});
            return ((System.Xml.XmlNode)(results[0]));
        }
        
        /// <remarks/>
        public void ModifyLotAttributeAsync(string lot, string name, string value) {
            this.ModifyLotAttributeAsync(lot, name, value, null);
        }
        
        /// <remarks/>
        public void ModifyLotAttributeAsync(string lot, string name, string value, object userState) {
            if ((this.ModifyLotAttributeOperationCompleted == null)) {
                this.ModifyLotAttributeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnModifyLotAttributeOperationCompleted);
            }
            this.InvokeAsync("ModifyLotAttribute", new object[] {
                        lot,
                        name,
                        value}, this.ModifyLotAttributeOperationCompleted, userState);
        }
        
        private void OnModifyLotAttributeOperationCompleted(object arg) {
            if ((this.ModifyLotAttributeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ModifyLotAttributeCompleted(this, new ModifyLotAttributeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/FutureHoldSetupByDiffusionBatch", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Xml.XmlNode FutureHoldSetupByDiffusionBatch(string DiffusionBatch, string spec, string specRev, string holdReason, string comment, string holdlocation) {
            object[] results = this.Invoke("FutureHoldSetupByDiffusionBatch", new object[] {
                        DiffusionBatch,
                        spec,
                        specRev,
                        holdReason,
                        comment,
                        holdlocation});
            return ((System.Xml.XmlNode)(results[0]));
        }
        
        /// <remarks/>
        public void FutureHoldSetupByDiffusionBatchAsync(string DiffusionBatch, string spec, string specRev, string holdReason, string comment, string holdlocation) {
            this.FutureHoldSetupByDiffusionBatchAsync(DiffusionBatch, spec, specRev, holdReason, comment, holdlocation, null);
        }
        
        /// <remarks/>
        public void FutureHoldSetupByDiffusionBatchAsync(string DiffusionBatch, string spec, string specRev, string holdReason, string comment, string holdlocation, object userState) {
            if ((this.FutureHoldSetupByDiffusionBatchOperationCompleted == null)) {
                this.FutureHoldSetupByDiffusionBatchOperationCompleted = new System.Threading.SendOrPostCallback(this.OnFutureHoldSetupByDiffusionBatchOperationCompleted);
            }
            this.InvokeAsync("FutureHoldSetupByDiffusionBatch", new object[] {
                        DiffusionBatch,
                        spec,
                        specRev,
                        holdReason,
                        comment,
                        holdlocation}, this.FutureHoldSetupByDiffusionBatchOperationCompleted, userState);
        }
        
        private void OnFutureHoldSetupByDiffusionBatchOperationCompleted(object arg) {
            if ((this.FutureHoldSetupByDiffusionBatchCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.FutureHoldSetupByDiffusionBatchCompleted(this, new FutureHoldSetupByDiffusionBatchCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/RemoveFutureHoldSetup", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ResultMessage RemoveFutureHoldSetup(string FutureHoldSetupName) {
            object[] results = this.Invoke("RemoveFutureHoldSetup", new object[] {
                        FutureHoldSetupName});
            return ((ResultMessage)(results[0]));
        }
        
        /// <remarks/>
        public void RemoveFutureHoldSetupAsync(string FutureHoldSetupName) {
            this.RemoveFutureHoldSetupAsync(FutureHoldSetupName, null);
        }
        
        /// <remarks/>
        public void RemoveFutureHoldSetupAsync(string FutureHoldSetupName, object userState) {
            if ((this.RemoveFutureHoldSetupOperationCompleted == null)) {
                this.RemoveFutureHoldSetupOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRemoveFutureHoldSetupOperationCompleted);
            }
            this.InvokeAsync("RemoveFutureHoldSetup", new object[] {
                        FutureHoldSetupName}, this.RemoveFutureHoldSetupOperationCompleted, userState);
        }
        
        private void OnRemoveFutureHoldSetupOperationCompleted(object arg) {
            if ((this.RemoveFutureHoldSetupCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RemoveFutureHoldSetupCompleted(this, new RemoveFutureHoldSetupCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ModifyLotItems", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ResultMessage ModifyLotItems(string lot, string item, string waferSliceNum, string ocrId, string qty, string sortEquipment) {
            object[] results = this.Invoke("ModifyLotItems", new object[] {
                        lot,
                        item,
                        waferSliceNum,
                        ocrId,
                        qty,
                        sortEquipment});
            return ((ResultMessage)(results[0]));
        }
        
        /// <remarks/>
        public void ModifyLotItemsAsync(string lot, string item, string waferSliceNum, string ocrId, string qty, string sortEquipment) {
            this.ModifyLotItemsAsync(lot, item, waferSliceNum, ocrId, qty, sortEquipment, null);
        }
        
        /// <remarks/>
        public void ModifyLotItemsAsync(string lot, string item, string waferSliceNum, string ocrId, string qty, string sortEquipment, object userState) {
            if ((this.ModifyLotItemsOperationCompleted == null)) {
                this.ModifyLotItemsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnModifyLotItemsOperationCompleted);
            }
            this.InvokeAsync("ModifyLotItems", new object[] {
                        lot,
                        item,
                        waferSliceNum,
                        ocrId,
                        qty,
                        sortEquipment}, this.ModifyLotItemsOperationCompleted, userState);
        }
        
        private void OnModifyLotItemsOperationCompleted(object arg) {
            if ((this.ModifyLotItemsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ModifyLotItemsCompleted(this, new ModifyLotItemsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/LotHoldDispose", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ResultMessage LotHoldDispose(string container, string reason, string comment) {
            object[] results = this.Invoke("LotHoldDispose", new object[] {
                        container,
                        reason,
                        comment});
            return ((ResultMessage)(results[0]));
        }
        
        /// <remarks/>
        public void LotHoldDisposeAsync(string container, string reason, string comment) {
            this.LotHoldDisposeAsync(container, reason, comment, null);
        }
        
        /// <remarks/>
        public void LotHoldDisposeAsync(string container, string reason, string comment, object userState) {
            if ((this.LotHoldDisposeOperationCompleted == null)) {
                this.LotHoldDisposeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLotHoldDisposeOperationCompleted);
            }
            this.InvokeAsync("LotHoldDispose", new object[] {
                        container,
                        reason,
                        comment}, this.LotHoldDisposeOperationCompleted, userState);
        }
        
        private void OnLotHoldDisposeOperationCompleted(object arg) {
            if ((this.LotHoldDisposeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.LotHoldDisposeCompleted(this, new LotHoldDisposeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/LotHoldTransaction", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ResultMessage LotHoldTransaction(string container) {
            object[] results = this.Invoke("LotHoldTransaction", new object[] {
                        container});
            return ((ResultMessage)(results[0]));
        }
        
        /// <remarks/>
        public void LotHoldTransactionAsync(string container) {
            this.LotHoldTransactionAsync(container, null);
        }
        
        /// <remarks/>
        public void LotHoldTransactionAsync(string container, object userState) {
            if ((this.LotHoldTransactionOperationCompleted == null)) {
                this.LotHoldTransactionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLotHoldTransactionOperationCompleted);
            }
            this.InvokeAsync("LotHoldTransaction", new object[] {
                        container}, this.LotHoldTransactionOperationCompleted, userState);
        }
        
        private void OnLotHoldTransactionOperationCompleted(object arg) {
            if ((this.LotHoldTransactionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.LotHoldTransactionCompleted(this, new LotHoldTransactionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/RemoveLotFutureHold", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ResultMessage RemoveLotFutureHold(string container, string specName) {
            object[] results = this.Invoke("RemoveLotFutureHold", new object[] {
                        container,
                        specName});
            return ((ResultMessage)(results[0]));
        }
        
        /// <remarks/>
        public void RemoveLotFutureHoldAsync(string container, string specName) {
            this.RemoveLotFutureHoldAsync(container, specName, null);
        }
        
        /// <remarks/>
        public void RemoveLotFutureHoldAsync(string container, string specName, object userState) {
            if ((this.RemoveLotFutureHoldOperationCompleted == null)) {
                this.RemoveLotFutureHoldOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRemoveLotFutureHoldOperationCompleted);
            }
            this.InvokeAsync("RemoveLotFutureHold", new object[] {
                        container,
                        specName}, this.RemoveLotFutureHoldOperationCompleted, userState);
        }
        
        private void OnRemoveLotFutureHoldOperationCompleted(object arg) {
            if ((this.RemoveLotFutureHoldCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RemoveLotFutureHoldCompleted(this, new RemoveLotFutureHoldCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/LotModifyMarkingContent", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Xml.XmlNode LotModifyMarkingContent(System.Xml.XmlNode Markinformation) {
            object[] results = this.Invoke("LotModifyMarkingContent", new object[] {
                        Markinformation});
            return ((System.Xml.XmlNode)(results[0]));
        }
        
        /// <remarks/>
        public void LotModifyMarkingContentAsync(System.Xml.XmlNode Markinformation) {
            this.LotModifyMarkingContentAsync(Markinformation, null);
        }
        
        /// <remarks/>
        public void LotModifyMarkingContentAsync(System.Xml.XmlNode Markinformation, object userState) {
            if ((this.LotModifyMarkingContentOperationCompleted == null)) {
                this.LotModifyMarkingContentOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLotModifyMarkingContentOperationCompleted);
            }
            this.InvokeAsync("LotModifyMarkingContent", new object[] {
                        Markinformation}, this.LotModifyMarkingContentOperationCompleted, userState);
        }
        
        private void OnLotModifyMarkingContentOperationCompleted(object arg) {
            if ((this.LotModifyMarkingContentCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.LotModifyMarkingContentCompleted(this, new LotModifyMarkingContentCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AddVendorName", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ResultMessage AddVendorName(string VendorName) {
            object[] results = this.Invoke("AddVendorName", new object[] {
                        VendorName});
            return ((ResultMessage)(results[0]));
        }
        
        /// <remarks/>
        public void AddVendorNameAsync(string VendorName) {
            this.AddVendorNameAsync(VendorName, null);
        }
        
        /// <remarks/>
        public void AddVendorNameAsync(string VendorName, object userState) {
            if ((this.AddVendorNameOperationCompleted == null)) {
                this.AddVendorNameOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAddVendorNameOperationCompleted);
            }
            this.InvokeAsync("AddVendorName", new object[] {
                        VendorName}, this.AddVendorNameOperationCompleted, userState);
        }
        
        private void OnAddVendorNameOperationCompleted(object arg) {
            if ((this.AddVendorNameCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AddVendorNameCompleted(this, new AddVendorNameCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Printing", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ResultMessage Printing(string PrintingSetup, string Lot, string Box1, string Box2) {
            object[] results = this.Invoke("Printing", new object[] {
                        PrintingSetup,
                        Lot,
                        Box1,
                        Box2});
            return ((ResultMessage)(results[0]));
        }
        
        /// <remarks/>
        public void PrintingAsync(string PrintingSetup, string Lot, string Box1, string Box2) {
            this.PrintingAsync(PrintingSetup, Lot, Box1, Box2, null);
        }
        
        /// <remarks/>
        public void PrintingAsync(string PrintingSetup, string Lot, string Box1, string Box2, object userState) {
            if ((this.PrintingOperationCompleted == null)) {
                this.PrintingOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPrintingOperationCompleted);
            }
            this.InvokeAsync("Printing", new object[] {
                        PrintingSetup,
                        Lot,
                        Box1,
                        Box2}, this.PrintingOperationCompleted, userState);
        }
        
        private void OnPrintingOperationCompleted(object arg) {
            if ((this.PrintingCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.PrintingCompleted(this, new PrintingCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/LotAddSI", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Xml.XmlNode LotAddSI(string container, string SIName, string SIComments, string employee) {
            object[] results = this.Invoke("LotAddSI", new object[] {
                        container,
                        SIName,
                        SIComments,
                        employee});
            return ((System.Xml.XmlNode)(results[0]));
        }
        
        /// <remarks/>
        public void LotAddSIAsync(string container, string SIName, string SIComments, string employee) {
            this.LotAddSIAsync(container, SIName, SIComments, employee, null);
        }
        
        /// <remarks/>
        public void LotAddSIAsync(string container, string SIName, string SIComments, string employee, object userState) {
            if ((this.LotAddSIOperationCompleted == null)) {
                this.LotAddSIOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLotAddSIOperationCompleted);
            }
            this.InvokeAsync("LotAddSI", new object[] {
                        container,
                        SIName,
                        SIComments,
                        employee}, this.LotAddSIOperationCompleted, userState);
        }
        
        private void OnLotAddSIOperationCompleted(object arg) {
            if ((this.LotAddSICompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.LotAddSICompleted(this, new LotAddSICompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/LotReleaseSI", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Xml.XmlNode LotReleaseSI(string container, string SIName, string SIComments, string Comments, string employee) {
            object[] results = this.Invoke("LotReleaseSI", new object[] {
                        container,
                        SIName,
                        SIComments,
                        Comments,
                        employee});
            return ((System.Xml.XmlNode)(results[0]));
        }
        
        /// <remarks/>
        public void LotReleaseSIAsync(string container, string SIName, string SIComments, string Comments, string employee) {
            this.LotReleaseSIAsync(container, SIName, SIComments, Comments, employee, null);
        }
        
        /// <remarks/>
        public void LotReleaseSIAsync(string container, string SIName, string SIComments, string Comments, string employee, object userState) {
            if ((this.LotReleaseSIOperationCompleted == null)) {
                this.LotReleaseSIOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLotReleaseSIOperationCompleted);
            }
            this.InvokeAsync("LotReleaseSI", new object[] {
                        container,
                        SIName,
                        SIComments,
                        Comments,
                        employee}, this.LotReleaseSIOperationCompleted, userState);
        }
        
        private void OnLotReleaseSIOperationCompleted(object arg) {
            if ((this.LotReleaseSICompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.LotReleaseSICompleted(this, new LotReleaseSICompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/LotReleaseSIWithNcrbNumber", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Xml.XmlNode LotReleaseSIWithNcrbNumber(string container, string SIName, string SIComments, string Comments, string eNCRB, string employee) {
            object[] results = this.Invoke("LotReleaseSIWithNcrbNumber", new object[] {
                        container,
                        SIName,
                        SIComments,
                        Comments,
                        eNCRB,
                        employee});
            return ((System.Xml.XmlNode)(results[0]));
        }
        
        /// <remarks/>
        public void LotReleaseSIWithNcrbNumberAsync(string container, string SIName, string SIComments, string Comments, string eNCRB, string employee) {
            this.LotReleaseSIWithNcrbNumberAsync(container, SIName, SIComments, Comments, eNCRB, employee, null);
        }
        
        /// <remarks/>
        public void LotReleaseSIWithNcrbNumberAsync(string container, string SIName, string SIComments, string Comments, string eNCRB, string employee, object userState) {
            if ((this.LotReleaseSIWithNcrbNumberOperationCompleted == null)) {
                this.LotReleaseSIWithNcrbNumberOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLotReleaseSIWithNcrbNumberOperationCompleted);
            }
            this.InvokeAsync("LotReleaseSIWithNcrbNumber", new object[] {
                        container,
                        SIName,
                        SIComments,
                        Comments,
                        eNCRB,
                        employee}, this.LotReleaseSIWithNcrbNumberOperationCompleted, userState);
        }
        
        private void OnLotReleaseSIWithNcrbNumberOperationCompleted(object arg) {
            if ((this.LotReleaseSIWithNcrbNumberCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.LotReleaseSIWithNcrbNumberCompleted(this, new LotReleaseSIWithNcrbNumberCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetQueryResult", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Xml.XmlNode GetQueryResult(string queryname, string paramnames, string paramvalues) {
            object[] results = this.Invoke("GetQueryResult", new object[] {
                        queryname,
                        paramnames,
                        paramvalues});
            return ((System.Xml.XmlNode)(results[0]));
        }
        
        /// <remarks/>
        public void GetQueryResultAsync(string queryname, string paramnames, string paramvalues) {
            this.GetQueryResultAsync(queryname, paramnames, paramvalues, null);
        }
        
        /// <remarks/>
        public void GetQueryResultAsync(string queryname, string paramnames, string paramvalues, object userState) {
            if ((this.GetQueryResultOperationCompleted == null)) {
                this.GetQueryResultOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetQueryResultOperationCompleted);
            }
            this.InvokeAsync("GetQueryResult", new object[] {
                        queryname,
                        paramnames,
                        paramvalues}, this.GetQueryResultOperationCompleted, userState);
        }
        
        private void OnGetQueryResultOperationCompleted(object arg) {
            if ((this.GetQueryResultCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetQueryResultCompleted(this, new GetQueryResultCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ModifyLotReels", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Xml.XmlNode ModifyLotReels(string container, string reels) {
            object[] results = this.Invoke("ModifyLotReels", new object[] {
                        container,
                        reels});
            return ((System.Xml.XmlNode)(results[0]));
        }
        
        /// <remarks/>
        public void ModifyLotReelsAsync(string container, string reels) {
            this.ModifyLotReelsAsync(container, reels, null);
        }
        
        /// <remarks/>
        public void ModifyLotReelsAsync(string container, string reels, object userState) {
            if ((this.ModifyLotReelsOperationCompleted == null)) {
                this.ModifyLotReelsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnModifyLotReelsOperationCompleted);
            }
            this.InvokeAsync("ModifyLotReels", new object[] {
                        container,
                        reels}, this.ModifyLotReelsOperationCompleted, userState);
        }
        
        private void OnModifyLotReelsOperationCompleted(object arg) {
            if ((this.ModifyLotReelsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ModifyLotReelsCompleted(this, new ModifyLotReelsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/LotAddSiWithNCRB", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Xml.XmlNode LotAddSiWithNCRB(string Container, string SiName, string SiComments, string Employee, string NCRB) {
            object[] results = this.Invoke("LotAddSiWithNCRB", new object[] {
                        Container,
                        SiName,
                        SiComments,
                        Employee,
                        NCRB});
            return ((System.Xml.XmlNode)(results[0]));
        }
        
        /// <remarks/>
        public void LotAddSiWithNCRBAsync(string Container, string SiName, string SiComments, string Employee, string NCRB) {
            this.LotAddSiWithNCRBAsync(Container, SiName, SiComments, Employee, NCRB, null);
        }
        
        /// <remarks/>
        public void LotAddSiWithNCRBAsync(string Container, string SiName, string SiComments, string Employee, string NCRB, object userState) {
            if ((this.LotAddSiWithNCRBOperationCompleted == null)) {
                this.LotAddSiWithNCRBOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLotAddSiWithNCRBOperationCompleted);
            }
            this.InvokeAsync("LotAddSiWithNCRB", new object[] {
                        Container,
                        SiName,
                        SiComments,
                        Employee,
                        NCRB}, this.LotAddSiWithNCRBOperationCompleted, userState);
        }
        
        private void OnLotAddSiWithNCRBOperationCompleted(object arg) {
            if ((this.LotAddSiWithNCRBCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.LotAddSiWithNCRBCompleted(this, new LotAddSiWithNCRBCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/LotReleaseSiWithNCRB", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Xml.XmlNode LotReleaseSiWithNCRB(string employee, string NCRB) {
            object[] results = this.Invoke("LotReleaseSiWithNCRB", new object[] {
                        employee,
                        NCRB});
            return ((System.Xml.XmlNode)(results[0]));
        }
        
        /// <remarks/>
        public void LotReleaseSiWithNCRBAsync(string employee, string NCRB) {
            this.LotReleaseSiWithNCRBAsync(employee, NCRB, null);
        }
        
        /// <remarks/>
        public void LotReleaseSiWithNCRBAsync(string employee, string NCRB, object userState) {
            if ((this.LotReleaseSiWithNCRBOperationCompleted == null)) {
                this.LotReleaseSiWithNCRBOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLotReleaseSiWithNCRBOperationCompleted);
            }
            this.InvokeAsync("LotReleaseSiWithNCRB", new object[] {
                        employee,
                        NCRB}, this.LotReleaseSiWithNCRBOperationCompleted, userState);
        }
        
        private void OnLotReleaseSiWithNCRBOperationCompleted(object arg) {
            if ((this.LotReleaseSiWithNCRBCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.LotReleaseSiWithNCRBCompleted(this, new LotReleaseSiWithNCRBCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/LotEquipmentReservation", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Xml.XmlNode LotEquipmentReservation(string Container, string Tester) {
            object[] results = this.Invoke("LotEquipmentReservation", new object[] {
                        Container,
                        Tester});
            return ((System.Xml.XmlNode)(results[0]));
        }
        
        /// <remarks/>
        public void LotEquipmentReservationAsync(string Container, string Tester) {
            this.LotEquipmentReservationAsync(Container, Tester, null);
        }
        
        /// <remarks/>
        public void LotEquipmentReservationAsync(string Container, string Tester, object userState) {
            if ((this.LotEquipmentReservationOperationCompleted == null)) {
                this.LotEquipmentReservationOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLotEquipmentReservationOperationCompleted);
            }
            this.InvokeAsync("LotEquipmentReservation", new object[] {
                        Container,
                        Tester}, this.LotEquipmentReservationOperationCompleted, userState);
        }
        
        private void OnLotEquipmentReservationOperationCompleted(object arg) {
            if ((this.LotEquipmentReservationCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.LotEquipmentReservationCompleted(this, new LotEquipmentReservationCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/LotCombine", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Xml.XmlNode LotCombine(string MainLot, string FromLot, string Qty) {
            object[] results = this.Invoke("LotCombine", new object[] {
                        MainLot,
                        FromLot,
                        Qty});
            return ((System.Xml.XmlNode)(results[0]));
        }
        
        /// <remarks/>
        public void LotCombineAsync(string MainLot, string FromLot, string Qty) {
            this.LotCombineAsync(MainLot, FromLot, Qty, null);
        }
        
        /// <remarks/>
        public void LotCombineAsync(string MainLot, string FromLot, string Qty, object userState) {
            if ((this.LotCombineOperationCompleted == null)) {
                this.LotCombineOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLotCombineOperationCompleted);
            }
            this.InvokeAsync("LotCombine", new object[] {
                        MainLot,
                        FromLot,
                        Qty}, this.LotCombineOperationCompleted, userState);
        }
        
        private void OnLotCombineOperationCompleted(object arg) {
            if ((this.LotCombineCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.LotCombineCompleted(this, new LotCombineCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AddEquipmentBlockStatus", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Xml.XmlNode AddEquipmentBlockStatus(string equipment, string blockCode, string reason, string comments) {
            object[] results = this.Invoke("AddEquipmentBlockStatus", new object[] {
                        equipment,
                        blockCode,
                        reason,
                        comments});
            return ((System.Xml.XmlNode)(results[0]));
        }
        
        /// <remarks/>
        public void AddEquipmentBlockStatusAsync(string equipment, string blockCode, string reason, string comments) {
            this.AddEquipmentBlockStatusAsync(equipment, blockCode, reason, comments, null);
        }
        
        /// <remarks/>
        public void AddEquipmentBlockStatusAsync(string equipment, string blockCode, string reason, string comments, object userState) {
            if ((this.AddEquipmentBlockStatusOperationCompleted == null)) {
                this.AddEquipmentBlockStatusOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAddEquipmentBlockStatusOperationCompleted);
            }
            this.InvokeAsync("AddEquipmentBlockStatus", new object[] {
                        equipment,
                        blockCode,
                        reason,
                        comments}, this.AddEquipmentBlockStatusOperationCompleted, userState);
        }
        
        private void OnAddEquipmentBlockStatusOperationCompleted(object arg) {
            if ((this.AddEquipmentBlockStatusCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AddEquipmentBlockStatusCompleted(this, new AddEquipmentBlockStatusCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/RealeaseEquipmentBlockStatus", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Xml.XmlNode RealeaseEquipmentBlockStatus(string equipment, string blockCode, string reason, string comments) {
            object[] results = this.Invoke("RealeaseEquipmentBlockStatus", new object[] {
                        equipment,
                        blockCode,
                        reason,
                        comments});
            return ((System.Xml.XmlNode)(results[0]));
        }
        
        /// <remarks/>
        public void RealeaseEquipmentBlockStatusAsync(string equipment, string blockCode, string reason, string comments) {
            this.RealeaseEquipmentBlockStatusAsync(equipment, blockCode, reason, comments, null);
        }
        
        /// <remarks/>
        public void RealeaseEquipmentBlockStatusAsync(string equipment, string blockCode, string reason, string comments, object userState) {
            if ((this.RealeaseEquipmentBlockStatusOperationCompleted == null)) {
                this.RealeaseEquipmentBlockStatusOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRealeaseEquipmentBlockStatusOperationCompleted);
            }
            this.InvokeAsync("RealeaseEquipmentBlockStatus", new object[] {
                        equipment,
                        blockCode,
                        reason,
                        comments}, this.RealeaseEquipmentBlockStatusOperationCompleted, userState);
        }
        
        private void OnRealeaseEquipmentBlockStatusOperationCompleted(object arg) {
            if ((this.RealeaseEquipmentBlockStatusCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RealeaseEquipmentBlockStatusCompleted(this, new RealeaseEquipmentBlockStatusCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ResultMessage {
        
        private int codeField;
        
        private string messageField;
        
        private object resultObjectField;
        
        private string detailMessageField;
        
        /// <remarks/>
        public int Code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
            }
        }
        
        /// <remarks/>
        public object ResultObject {
            get {
                return this.resultObjectField;
            }
            set {
                this.resultObjectField = value;
            }
        }
        
        /// <remarks/>
        public string DetailMessage {
            get {
                return this.detailMessageField;
            }
            set {
                this.detailMessageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void GetVersionCompletedEventHandler(object sender, GetVersionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetVersionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetVersionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Xml.XmlNode Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Xml.XmlNode)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void LotHoldCompletedEventHandler(object sender, LotHoldCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class LotHoldCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal LotHoldCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Xml.XmlNode Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Xml.XmlNode)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void LotReleaseCompletedEventHandler(object sender, LotReleaseCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class LotReleaseCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal LotReleaseCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Xml.XmlNode Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Xml.XmlNode)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void ModifyLotHoldcodeCompletedEventHandler(object sender, ModifyLotHoldcodeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ModifyLotHoldcodeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ModifyLotHoldcodeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Xml.XmlNode Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Xml.XmlNode)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void LotFutureHoldSetupCompletedEventHandler(object sender, LotFutureHoldSetupCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class LotFutureHoldSetupCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal LotFutureHoldSetupCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Xml.XmlNode Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Xml.XmlNode)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void ModifyLotAttributeCompletedEventHandler(object sender, ModifyLotAttributeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ModifyLotAttributeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ModifyLotAttributeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Xml.XmlNode Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Xml.XmlNode)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void FutureHoldSetupByDiffusionBatchCompletedEventHandler(object sender, FutureHoldSetupByDiffusionBatchCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class FutureHoldSetupByDiffusionBatchCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal FutureHoldSetupByDiffusionBatchCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Xml.XmlNode Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Xml.XmlNode)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void RemoveFutureHoldSetupCompletedEventHandler(object sender, RemoveFutureHoldSetupCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RemoveFutureHoldSetupCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RemoveFutureHoldSetupCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ResultMessage Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ResultMessage)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void ModifyLotItemsCompletedEventHandler(object sender, ModifyLotItemsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ModifyLotItemsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ModifyLotItemsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ResultMessage Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ResultMessage)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void LotHoldDisposeCompletedEventHandler(object sender, LotHoldDisposeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class LotHoldDisposeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal LotHoldDisposeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ResultMessage Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ResultMessage)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void LotHoldTransactionCompletedEventHandler(object sender, LotHoldTransactionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class LotHoldTransactionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal LotHoldTransactionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ResultMessage Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ResultMessage)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void RemoveLotFutureHoldCompletedEventHandler(object sender, RemoveLotFutureHoldCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RemoveLotFutureHoldCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RemoveLotFutureHoldCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ResultMessage Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ResultMessage)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void LotModifyMarkingContentCompletedEventHandler(object sender, LotModifyMarkingContentCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class LotModifyMarkingContentCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal LotModifyMarkingContentCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Xml.XmlNode Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Xml.XmlNode)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void AddVendorNameCompletedEventHandler(object sender, AddVendorNameCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AddVendorNameCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AddVendorNameCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ResultMessage Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ResultMessage)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void PrintingCompletedEventHandler(object sender, PrintingCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PrintingCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal PrintingCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ResultMessage Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ResultMessage)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void LotAddSICompletedEventHandler(object sender, LotAddSICompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class LotAddSICompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal LotAddSICompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Xml.XmlNode Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Xml.XmlNode)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void LotReleaseSICompletedEventHandler(object sender, LotReleaseSICompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class LotReleaseSICompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal LotReleaseSICompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Xml.XmlNode Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Xml.XmlNode)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void LotReleaseSIWithNcrbNumberCompletedEventHandler(object sender, LotReleaseSIWithNcrbNumberCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class LotReleaseSIWithNcrbNumberCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal LotReleaseSIWithNcrbNumberCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Xml.XmlNode Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Xml.XmlNode)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void GetQueryResultCompletedEventHandler(object sender, GetQueryResultCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetQueryResultCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetQueryResultCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Xml.XmlNode Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Xml.XmlNode)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void ModifyLotReelsCompletedEventHandler(object sender, ModifyLotReelsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ModifyLotReelsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ModifyLotReelsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Xml.XmlNode Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Xml.XmlNode)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void LotAddSiWithNCRBCompletedEventHandler(object sender, LotAddSiWithNCRBCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class LotAddSiWithNCRBCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal LotAddSiWithNCRBCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Xml.XmlNode Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Xml.XmlNode)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void LotReleaseSiWithNCRBCompletedEventHandler(object sender, LotReleaseSiWithNCRBCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class LotReleaseSiWithNCRBCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal LotReleaseSiWithNCRBCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Xml.XmlNode Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Xml.XmlNode)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void LotEquipmentReservationCompletedEventHandler(object sender, LotEquipmentReservationCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class LotEquipmentReservationCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal LotEquipmentReservationCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Xml.XmlNode Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Xml.XmlNode)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void LotCombineCompletedEventHandler(object sender, LotCombineCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class LotCombineCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal LotCombineCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Xml.XmlNode Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Xml.XmlNode)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void AddEquipmentBlockStatusCompletedEventHandler(object sender, AddEquipmentBlockStatusCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AddEquipmentBlockStatusCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AddEquipmentBlockStatusCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Xml.XmlNode Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Xml.XmlNode)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void RealeaseEquipmentBlockStatusCompletedEventHandler(object sender, RealeaseEquipmentBlockStatusCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RealeaseEquipmentBlockStatusCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RealeaseEquipmentBlockStatusCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Xml.XmlNode Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Xml.XmlNode)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591