using System.Net;
using System.Text;
using SchedulerMonitor.Infrastructure;
using SchedulerMonitor.Models;

namespace SchedulerMonitor.Services;

public sealed record ReportContent(string Subject, string Html, string FilePath);

public sealed class ReportBuilder
{
    private readonly AppPaths _paths;

    public ReportBuilder(AppPaths paths) => _paths = paths;

    public ReportContent BuildAndSave(MonitorRunResult run)
    {
        var ordered = run.Tasks.OrderBy(task => SortOrder(task.Status))
            .ThenBy(task => task.ServerName).ThenBy(task => task.DisplayName).ToList();
        var failed = Count(run, MonitorStatus.Failed);
        var unreachable = Count(run, MonitorStatus.Unreachable);
        var overdue = Count(run, MonitorStatus.Overdue);
        var longRunning = Count(run, MonitorStatus.LongRunning);
        var abnormal = Count(run, MonitorStatus.Abnormal);
        var disabled = Count(run, MonitorStatus.Disabled);
        var problemParts = new List<string>();
        if (failed > 0) problemParts.Add($"{failed} Failed");
        if (unreachable > 0) problemParts.Add($"{unreachable} Unreachable");
        if (overdue > 0) problemParts.Add($"{overdue} Overdue");
        if (longRunning > 0) problemParts.Add($"{longRunning} Long Running");
        if (abnormal > 0) problemParts.Add($"{abnormal} Abnormal");
        if (disabled > 0) problemParts.Add($"{disabled} Disabled");
        var subject = problemParts.Count == 0
            ? $"[Scheduler Monitor] All Jobs OK - {run.CompletedAt:dd MMM yyyy}"
            : $"[Scheduler Monitor] {string.Join(" / ", problemParts)} - {run.CompletedAt:dd MMM yyyy}";

        var html = BuildHtml(run, ordered);
        var filePath = Path.Combine(_paths.ReportDirectory,
            $"SchedulerStatus_{run.CompletedAt:yyyy-MM-dd_HHmmss}.html");
        File.WriteAllText(filePath, html, Encoding.UTF8);
        return new ReportContent(subject, html, filePath);
    }

    private static string BuildHtml(MonitorRunResult run, IReadOnlyList<TaskMonitorResult> ordered)
    {
        var attention = ordered.Where(task => task.Status is MonitorStatus.Failed or MonitorStatus.Overdue
            or MonitorStatus.Disabled or MonitorStatus.Unreachable or MonitorStatus.LongRunning
            or MonitorStatus.Abnormal).ToList();
        var longRunningCount = Count(run, MonitorStatus.LongRunning);
        var sb = new StringBuilder();
        sb.Append("<!doctype html><html><head><meta charset='utf-8'><style>")
          .Append("body{font-family:Segoe UI,Arial,sans-serif;color:#263238;margin:0;background:#f5f7f8}")
          .Append(".wrap{max-width:980px;margin:20px auto;background:#fff;border:1px solid #dde4e6}")
          .Append(".head{background:#036F7B;color:#fff;padding:20px 24px}.head h1{font-size:21px;margin:0 0 5px}")
          .Append(".content{padding:22px 24px}.cards{display:flex;gap:8px;flex-wrap:wrap;margin:12px 0 24px}")
          .Append(".card{min-width:105px;border:1px solid #dfe7e8;padding:10px 12px}.num{font-size:22px;font-weight:700;color:#036F7B}")
          .Append("table{width:100%;border-collapse:collapse;margin-bottom:22px}th{background:#edf3f4;text-align:left}")
          .Append("th,td{padding:9px 8px;border-bottom:1px solid #e4e9ea;font-size:13px}.status{font-weight:700}")
          .Append(".SUCCESS{color:#207245}.RUNNING,.PENDING{color:#1261a0}.OVERDUE,.DISABLED{color:#c06400}")
          .Append(".LONGRUNNING{color:#c64a00}.ABNORMAL{color:#922b7a}")
          .Append(".FAILED,.UNREACHABLE{color:#b42318}.muted{color:#617177}.foot{font-size:12px;color:#617177;margin-top:18px}")
          .Append("</style></head><body><div class='wrap'><div class='head'><h1>TASK SCHEDULER DAILY STATUS</h1>")
          .Append($"<div>{run.CompletedAt:dd MMMM yyyy | HH:mm}</div></div><div class='content'>")
          .Append("<h2>Summary</h2><div class='cards'>")
          .Append(Card("Servers", run.ServerCount)).Append(Card("Tasks", run.Tasks.Count))
          .Append(Card("Success", Count(run, MonitorStatus.Success))).Append(Card("Running", Count(run, MonitorStatus.Running)))
          .Append(Card("Long Running", longRunningCount)).Append(Card("Abnormal", Count(run, MonitorStatus.Abnormal)))
          .Append(Card("Pending", Count(run, MonitorStatus.Pending))).Append(Card("Problems", run.Tasks.Count(task => task.Status is MonitorStatus.Failed or MonitorStatus.Overdue or MonitorStatus.Disabled or MonitorStatus.Unreachable or MonitorStatus.LongRunning or MonitorStatus.Abnormal)))
          .Append("</div>");

        if (attention.Count > 0)
        {
            sb.Append("<h2>Attention Required</h2>").Append(BuildTable(attention));
        }

        sb.Append("<h2>All Tasks</h2>").Append(BuildTable(ordered))
          .Append("<div class='foot'>Generated by Scheduler Monitor. Windows result codes and Task Scheduler event IDs are retained for troubleshooting.</div>")
          .Append("</div></div></body></html>");
        return sb.ToString();
    }

    private static string BuildTable(IReadOnlyList<TaskMonitorResult> tasks)
    {
        var sb = new StringBuilder("<table><thead><tr><th>Server</th><th>Task</th><th>Status</th><th>Running For</th><th>Events</th><th>Last Run</th><th>Result</th><th>Detail</th></tr></thead><tbody>");
        foreach (var task in tasks)
        {
            sb.Append("<tr>")
              .Append(Td(task.ServerName)).Append(Td(task.DisplayName))
              .Append($"<td class='status {task.StatusCode}'>{task.StatusText}</td>")
              .Append(Td(task.RunningFor is { } elapsed ? MonitoringService.Describe(elapsed) : "-"))
              .Append(Td(string.IsNullOrWhiteSpace(task.EventSummary) ? "-" : task.EventSummary))
              .Append(Td(task.LastRunTime?.ToString("dd-MMM-yyyy HH:mm") ?? "-"))
              .Append(Td(string.IsNullOrWhiteSpace(task.LastResult) ? "-" : task.LastResult))
              .Append(Td(task.Detail)).Append("</tr>");
        }
        return sb.Append("</tbody></table>").ToString();
    }

    private static string Card(string label, int value) =>
        $"<div class='card'><div class='num'>{value}</div><div>{WebUtility.HtmlEncode(label)}</div></div>";
    private static string Td(string value) => $"<td>{WebUtility.HtmlEncode(value)}</td>";
    private static int Count(MonitorRunResult run, MonitorStatus status) => run.Tasks.Count(task => task.Status == status);
    private static int SortOrder(MonitorStatus status) => status switch
    {
        MonitorStatus.Failed => 0, MonitorStatus.Unreachable => 1, MonitorStatus.Abnormal => 2,
        MonitorStatus.Overdue => 3, MonitorStatus.Disabled => 4, MonitorStatus.LongRunning => 5,
        MonitorStatus.Running => 6, MonitorStatus.Pending => 7, _ => 8
    };
}
